version: '3'

services:
  softether:
    image: croc/softether
    volumes:
      - './logs/packet_log:/opt/vpnserver/packet_log'
      - './logs/security_log:/opt/vpnserver/security_log'
      - './logs/server_log:/opt/vpnserver/server_log'
      - './config/backup.vpn_server.config:/opt/vpnserver/backup.vpn_server.config'
      - './config/chain_certs:/opt/vpnserver/chain_certs'
      - './config/vpn_server.config:/opt/vpnserver/vpn_server.config'
      - '/etc/localtime:/etc/localtime:ro'
    privileged: true
    network_mode: host
    restart: unless-stopped 
